language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DOCTRINE_VERSION=2.1.*
  - DOCTRINE_VERSION=2.2.*
  - DOCTRINE_VERSION=2.3.*
  - DOCTRINE_VERSION=2.4.*
  - DOCTRINE_VERSION=2.5.*@dev

install:
  - composer self-update
  - composer install
  - composer require --prefer-source --dev doctrine/orm:${DOCTRINE_VERSION}

notifications:
  email: false

script: vendor/bin/phpunit
